import { NextResponse } from "next/server";
import puppeteer from "puppeteer-core";
import chromium from "@sparticuz/chromium";
import { getCurrentUser, isAdmin } from "@/lib/auth";
import { getContractWithSignatures } from "@/lib/data/contract";
import { buildContractHtml } from "@/lib/contract-pdf";

export const runtime = "nodejs";
export const maxDuration = 30;

// Arabic text shaping/bidi is genuinely hard to get right by hand (see git history: an
// earlier version manually reshaped + reversed + repositioned text for pdfkit, which kept
// producing subtly wrong output). A real browser engine already does this correctly, so the
// PDF is generated by rendering an HTML page and printing it, instead of drawing glyphs
// ourselves.
async function buildPdfBuffer(html: string): Promise<Buffer> {
  const browser = await puppeteer.launch({
    args: chromium.args,
    executablePath: await chromium.executablePath(),
    headless: true,
  });

  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "load" });
    const pdf = await page.pdf({
      format: "A4",
      margin: { top: "20mm", bottom: "20mm", left: "18mm", right: "18mm" },
      printBackground: true,
    });
    return Buffer.from(pdf);
  } finally {
    await browser.close();
  }
}

export async function GET() {
  const user = await getCurrentUser();
  if (!user || !isAdmin(user.role)) return new NextResponse("Unauthorized", { status: 401 });

  const contract = await getContractWithSignatures();
  if (!contract) return new NextResponse("Not found", { status: 404 });

  const html = buildContractHtml(
    contract.renderedContent,
    contract.signatures.map((s) => ({ partnerName: s.partnerName, signedAt: s.signedAt })),
  );
  const buffer = await buildPdfBuffer(html);

  return new NextResponse(new Uint8Array(buffer), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": 'attachment; filename="partnership_contract.pdf"',
      "Cache-Control": "no-store",
    },
  });
}
